/* Autogenerated by png2wx.pl on Wed Oct  2 16:06:25 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_remembrancer_active;
extern wxBitmap *_img_remembrancer_inactive;

#endif /* ICONS_H */
